
services:
  pgvector_openbrain:
    container_name: pgvector_openbrain
    image: pgvector/pgvector:0.8.0-pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 62zpmOEpVYGKHGRA
      POSTGRES_DB: postgres
    restart: always 
    ports:
      - "9438:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  rustfs_openbrain:
    container_name: rustfs_openbrain
    image: rustfs/rustfs:latest
    environment:
      RUSTFS_ACCESS_KEY: openbrain
      RUSTFS_SECRET_KEY: fdeglkTulJzQeePo
    restart: always
    ports:
      - "9002:9000"
      - "9003:9001"
    volumes:
      - ./rustfs_data:/data

