"""add organization_ai_config

Revision ID: 3a7406fe1a98
Revises: 1842f8fdcf90
Create Date: 2026-05-17 06:40:43.951156
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3a7406fe1a98'
down_revision: Union[str, None] = '1842f8fdcf90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_ai_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('folder_suggestion_system', sa.Text(), nullable=True),
    sa.Column('folder_tree_system', sa.Text(), nullable=True),
    sa.Column('chat_system', sa.Text(), nullable=True),
    sa.Column('rag_system', sa.Text(), nullable=True),
    sa.Column('ai_model', sa.String(length=128), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.add_column('organization_invitations', sa.Column('access_scope', sa.String(length=16), nullable=False))
    op.add_column('user_organization', sa.Column('access_scope', sa.String(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_organization', 'access_scope')
    op.drop_column('organization_invitations', 'access_scope')
    op.drop_table('organization_ai_config')
    # ### end Alembic commands ###
