"""add folders

Revision ID: 7ea851b2801c
Revises: aed12cf67fc2
Create Date: 2026-05-06 13:43:39.361083
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7ea851b2801c'
down_revision: Union[str, None] = 'aed12cf67fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
