"""fix recent_documents id to use server_default gen_random_uuid

Revision ID: 81f4206dd0eb
Revises: 8665f324b04a
Create Date: 2026-05-17 16:53:16.221105
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '81f4206dd0eb'
down_revision: Union[str, None] = '8665f324b04a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recent_documents', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recent_documents', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
