"""add recent_documents table

Revision ID: 8665f324b04a
Revises: cfcae3b5f326
Create Date: 2026-05-17 16:02:31.057548
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8665f324b04a'
down_revision: Union[str, None] = 'cfcae3b5f326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recent_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('note_id', sa.UUID(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'note_id', name='uq_recent_user_note')
    )
    op.drop_index('ix_chunks_search', table_name='chunks', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_chunks_search', 'chunks', [sa.text("to_tsvector('english'::regconfig, COALESCE(search_vector, ''::text))")], unique=False, postgresql_using='gin')
    op.drop_table('recent_documents')
    # ### end Alembic commands ###
