"""add attachment columns to notes

Revision ID: d68765f2a792
Revises: e04cb3f23106
Create Date: 2026-05-17 09:22:47.807842
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd68765f2a792'
down_revision: Union[str, None] = 'e04cb3f23106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_ai_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('folder_suggestion_system', sa.Text(), nullable=True),
    sa.Column('folder_tree_system', sa.Text(), nullable=True),
    sa.Column('chat_system', sa.Text(), nullable=True),
    sa.Column('rag_system', sa.Text(), nullable=True),
    sa.Column('ai_model', sa.String(length=128), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.add_column('notes', sa.Column('attachment_key', sa.String(length=512), nullable=True))
    op.add_column('notes', sa.Column('attachment_filename', sa.String(length=512), nullable=True))
    op.add_column('notes', sa.Column('attachment_size', sa.Integer(), nullable=True))
    op.add_column('notes', sa.Column('attachment_content_type', sa.String(length=256), nullable=True))
    op.alter_column('organization_invitations', 'access_scope',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_organization', 'access_scope',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_organization', 'access_scope',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'all'::character varying"),
               existing_nullable=False)
    op.alter_column('organization_invitations', 'access_scope',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'all'::character varying"),
               existing_nullable=False)
    op.drop_column('notes', 'attachment_content_type')
    op.drop_column('notes', 'attachment_size')
    op.drop_column('notes', 'attachment_filename')
    op.drop_column('notes', 'attachment_key')
    op.drop_table('organization_ai_config')
    # ### end Alembic commands ###
